### PR TITLE
enhance: allow data selection with arbitrary setpoint topics and variables

### PR DESCRIPTION
**Pull request by sjschlapbach**
**Problem Description:**
Until now, it was only possible to select data based on one of the 6 available `manual_control_setpoint` topics `aux1` to `aux6` when using the `data_selection=setpoint` option. It was requested that this mechanism should be more flexible and also accept other variables more flexibly.

**Proposed Solution:**
In addition to the `data_selection` attribute, the user can now provide a `selection_var` variable to the `make` command (with the syntax `topic_name/variable_name` - e.g. `manual_control_setpoint/aux1`). The corresponding variable will then be added to the topics that are loaded from the log file and used to identify relevant sections of the provided log.

Test command:
```
make estimate-model model=fixedwing_model log=path_to_ulog data_selection=setpoint selection_var=manual_control_setpoint/aux1
```

### CODE REVIEW

**Review by manumerous — APPROVED** [review]
That looks great. Thanks!

**Comment by manumerous** [comment]
I was just thinking that our generate_parametric_model.py contains quite a lot of logic and code. What do you think if we start modularizing some of the logic related to interactive and setpoint data selection into their own python modules to make the overall logic a bit more readable? Can be a different PR though.

**Review by Jaeyoung-Lim — APPROVED** [review]
@sjschlapbach Aweseome, thanks!

**Comment by Jaeyoung-Lim** [comment]
> I was just thinking that our generate_parametric_model.py contains quite a lot of logic and code. What do you think if we start modularizing some of the logic related to interactive and setpoint data selection into their own python modules to make the overall logic a bit more readable? Can be a different PR though.

Obviously, yes please :)

**Pull request merged**
