### PR TITLE
fix: ensure that model prediction with makefile command works as expected

### PR DESCRIPTION
**Pull request by sjschlapbach**
**Problem Description:**
This pull request addresses the problems described in #233. The prediction command does not work at the moment.

**Proposed Solution:**
The prediction script and/or the correspondingly used functions therein have been adapted to use the interfaces, which the estimation tasks also use. Additionally, only the model results and no fisher information is logged to resolve corresponding errors.

### CODE REVIEW

**Comment by sjschlapbach** [comment]
@manumerous The SysID pipeline also fails on the master branch as the dependency installation results in an error. Maybe you could take a look at it, since it might have something to do with the recent updates of the data selection package / submodule? It also seems to fail when installing the dependencies locally.

However, this should probably not hinder this PR from being merged, since model prediction is not covered by the pipeline at this point anyway...

**Review by Jaeyoung-Lim — APPROVED** [review]
Thanks for the fix!

**Comment by manumerous** [comment]
Thanks for addressing this!

**Comment by manumerous** [comment]
I am a bit short on time but will try look into the ci pipeline. Can you give me some feedback on what fails for you @sjschlapbach ?

**Comment by sjschlapbach** [comment]
Thanks @manumerous! I got the error message below when running `make install-dependencies`. Funnily, after downgrading the vpselector to version 1.0.1 and back to 1.0.2, the error does not appear anymore...

```bash
Collecting scs>=3.0
  Using cached scs-3.2.4.post1.tar.gz (1.5 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [12 lines of output]
      + meson setup /private/var/folders/k3/9kyl1flj25zbjltgt2hyxyf00000gn/T/pip-install-t7tvnsct/scs_ecb95fe3f57f4f39b664ba342507bf7f /private/var/folders/k3/9kyl1flj25zbjltgt2hyxyf00000gn/T/pip-install-t7tvnsct/scs_ecb95fe3f57f4f39b664ba342507bf7f/.mesonpy-4c_4ttn5 -Dbuildtype=release -Db_ndebug=if-release -Db_vscrt=md --native-file=/private/var/folders/k3/9kyl1flj25zbjltgt2hyxyf00000gn/T/pip-install-t7tvnsct/scs_ecb95fe3f57f4f39b664ba342507bf7f/.mesonpy-4c_4ttn5/meson-python-native-file.ini
      The Meson build system
      Version: 1.3.0
      Source dir: /private/var/folders/k3/9kyl1flj25zbjltgt2hyxyf00000gn/T/pip-install-t7tvnsct/scs_ecb95fe3f57f4f39b664ba342507bf7f
      Build dir: /private/var/folders/k3/9kyl1flj25zbjltgt2hyxyf00000gn/T/pip-install-t7tvnsct/scs_ecb95fe3f57f4f39b664ba342507bf7f/.mesonpy-4c_4ttn5
      Build type: native build
      Project name: scs
      Project version: undefined

      ../meson.build:1:0: ERROR: Compiler cc cannot compile programs.

      A full log can be found at /private/var/folders/k3/9kyl1flj25zbjltgt2hyxyf00000gn/T/pip-install-t7tvnsct/scs_ecb95fe3f57f4f39b664ba342507bf7f/.mesonpy-4c_4ttn5/meson-logs/meson-log.txt
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

**Comment by manumerous** [comment]
Hmm interesting. Maybe an issue with caching some old builds then. It works for me as well with a clean install

**Pull request merged**
