### PR TITLE
Fix Ci pipeline

### PR DESCRIPTION
**Pull request by manumerous**
Removed depreciated make install-full-dependencies since the vpselector is not just a pip package in requirements.txt

### CODE REVIEW

**Comment by manumerous** [comment]
It seems to be a timeout issue. Could be that the runner is running out of memory or a timeout is triggered. Have to investigate further. The same step works locally for me and @sjschlapbach the local dependencies installation worked.

**Comment by manumerous** [comment]
@Jaeyoung-Lim do we have access to some asl runners?

**Comment by Jaeyoung-Lim** [comment]
@manumerous Interesting, although the asl runners would have even less memory.

**Comment by manumerous** [comment]
It is just a suspicion my now. In the pipeline there is no obvious fail, the script is just terminated 🤔

**Comment by Jaeyoung-Lim** [comment]
- Self hosted runner being run here https://github.com/ethz-asl/data-driven-dynamics/pull/236

**Comment by manumerous** [comment]
Checked for the CI timeout. it is set to 45 min. So I doubt that was the issue. I think it was likely a memory issue due to us installing more dependencies through the vpselector (especially pyqt is heavy). Switching to the custom ASL runner seems to solve this issue.

**Comment by manumerous** [comment]
Please go ahead and merge directly if you agree with the changes.

**Review by Jaeyoung-Lim — APPROVED** [review]

**Pull request merged**
